### ISSUE TITLE
Change license from GPLV3

### ISSUE THREAD

**Issue by mhiley** [mhiley/rust-netcdf#9]
I'm going to change the license to MIT as requested by @bluss in #7 .

**Comment by bluss** [comment]
I've released GPLv3 software myself, and I don't want to force anyone to change their license. But it would be neat, it comes from a habit of much of Rust ecosystem being MIT or MIT/Apache-2.0 I guess and I haven't dwelled so long upon it. (But I have rewritten a small part of read-only netcdf so that I could use that instead :smile:; if nothing else that helps me understand the data model better..)

**Comment by mhiley** [comment]
fixed by #10
